//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guccho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int cId { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string duration { get; set; }
        public string level { get; set; }
    }
}
