//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guccho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        public int cId { get; set; }

        [DisplayName("Course Name")]
        [DataType(DataType.Text)]
        [Required]
        public string name { get; set; }

        [DisplayName("Course Code")]
        [DataType(DataType.Text)]
        [Required]
        public string code { get; set; }

        [DisplayName("Course Duration")]
        [DataType(DataType.Text)]
        public string duration { get; set; }

        [DisplayName("Level")]
        [DataType(DataType.Text)]
        public string level { get; set; }
    }
}
