//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guccho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string fullName { get; set; }
        public string password { get; set; }
        public string phoneNumber { get; set; }
        public string interests { get; set; }
        public string email { get; set; }
        public string sName { get; set; }
    }
}
